auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2024-01-01
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h

compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  delete_request_store: filesystem

limits_config:
  allow_structured_metadata: true
  volume_enabled: true
  retention_period: 168h
  retention_stream:
    - selector: '{stream="stderr"}'
      priority: 1
      period: 720h
    - selector: '{stream="error"}'
      priority: 1
      period: 720h
    - selector: '{level=~"(?i)(error|fatal|critical)"}'
      priority: 1
      period: 720h
    - selector: '{level=~"5[0-9]"}'
      priority: 1
      period: 720h

analytics:
  reporting_enabled: false
