global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: loki
    static_configs:
      - targets:
          - loki:3100

  - job_name: grafana
    metrics_path: /metrics
    static_configs:
      - targets:
          - grafana:3000

  - job_name: node
    static_configs:
      - targets:
          - host.docker.internal:9100

  - job_name: pm2
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:9209

  - job_name: rabbitmq-urlshortener
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:15692

  - job_name: rabbitmq-ocr
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:15693

  - job_name: backend-urlshortener
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:4000

  - job_name: redirector-urlshortener
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:4001

  - job_name: ocr-backend
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:4010

  - job_name: ocr-frontend
    metrics_path: /metrics
    static_configs:
      - targets:
          - host.docker.internal:3010

  - job_name: manga-reader
    metrics_path: /api/metrics
    static_configs:
      - targets:
          - manga-reader-backend-prod:4030
